global:
    scrape_interval: 5s
    external_labels:
        monitor: 'my-monitor'
scrape_configs:
    - job_name: 'prometheus'
      static_configs:
          - targets: ['prometheus:9090', 'cadvisor:8080', 'node-exporter:9100', 'metrics-gateway:9091']
